from .misc import *
from .terminal import *
from .modules import *

commands = {
    "len": {
        "type": "command",
        "func": lenght,
        "desc": "Count the length of a string",
        "min_args": 1,
        "max_args": -1,
        "pass_args": True,
    },
    "echo": {
        "type": "command",
        "func": echo,
        "desc": "Echo the input",
        "min_args": 1,
        "max_args": -1,
        "pass_args": True,
    },
    "help": {
        "type": "command",
        "func": get_help,
        "desc": "Get help on a command",
        "min_args": 0,
        "max_args": -1,
        "pass_args": False,
    },
    "exit": {
        "type": "command",
        "func": exit_term,
        "desc": "Exit the terminal",
        "min_args": 0,
        "max_args": -1,
        "pass_args": False,
    },
    "cls": {
        "type": "command",
        "func": cls,
        "desc": "Clear the terminal",
        "min_args": 0,
        "max_args": -1,
        "pass_args": False,
    },
    "terminal": {
        "type": "category",
        "resize": {
            "type": "command",
            "func": resize,
            "desc": "Resize the terminal screen",
            "min_args": 2,
            "max_args": 2,
            "pass_args": True,
        },
        "rescale": {
            "type": "command",
            "func": rescale,
            "desc": "Rescale the terminal screen",
            "min_args": 2,
            "max_args": 2,
            "pass_args": True,
        },
        "sset": {
            "type": "command",
            "func": sset,
            "desc": "Set a setting in the terminal",
            "min_args": 2,
            "max_args": -1,
            "pass_args": True,
        },
        "sget": {
            "type": "command",
            "func": sget,
            "desc": "Get a setting in the terminal",
            "min_args": 1,
            "max_args": 1,
            "pass_args": True,
        },
        "sreload": {
            "type": "command",
            "func": sreload,
            "desc": "Reload the settings in the terminal",
            "min_args": 0,
            "max_args": -1,
            "pass_args": False,
        },
    },
    "modules": {
        "type": "command",
        "func": modules,
        "desc": "Get and manage modules",
        "min_args": 0,
        "max_args": -1,
        "pass_args": True,
    },
}
